const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
let state=JSON.parse(localStorage.getItem('nebulaState')||'null')||{worldName:'',worldDesc:'',mood:'dream',memories:[],xp:0,wins:0,streak:1};
function save(){localStorage.setItem('nebulaState',JSON.stringify(state));render()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function render(){
 $('#worldName').value=state.worldName;$('#worldDesc').value=state.worldDesc;$('#mood').value=state.mood;$('#previewName').textContent=state.worldName||'عالم بلا اسم';$('#previewDesc').textContent=state.worldDesc||'اكتب شيئاً في المختبر لترى عالمك يولد.';
 $('#xp').textContent=state.xp;$('#memCount').textContent=state.memories.length;$('#gameCount').textContent=state.wins;$('#streak').textContent=state.streak;
 let pct=Math.min(100,Math.round((state.xp+state.memories.length*10)/2));$('#meterBar').style.width=pct+'%';$('#meterText').textContent=pct+'% مكتمل';
 $('#memoryList').innerHTML=state.memories.map((m,i)=>`<div class="memory"><b>${esc(m)}</b><small>نجمة #${i+1}</small></div>`).join('');
 const ach=[['🌱','أول بذرة',state.worldName.length>0],['⭐','أول نجمة',state.memories.length>0],['⚡','صائد البرق',state.wins>0],['🏆','ثلاثة انتصارات',state.wins>=3],['🌌','طاقة 100',state.xp>=100]];$('#achievements').innerHTML=ach.map(a=>`<div class="badge ${a[2]?'':'locked'}">${a[0]} <b>${a[1]}</b> ${a[2]?'✓':'—'}</div>`).join('');
 $('#finalTitle').textContent=state.worldName?`«${state.worldName}» أصبح حياً.`:'عالمك لم يكتمل بعد.';
 document.body.dataset.mood=state.mood;
}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
$('#saveWorld').onclick=()=>{state.worldName=$('#worldName').value.trim();state.worldDesc=$('#worldDesc').value.trim();state.mood=$('#mood').value;state.xp=Math.max(state.xp,20);save();toast('تم حفظ العالم ✦')};
$('#addMemory').onclick=()=>{const v=$('#memoryInput').value.trim();if(!v)return toast('اكتب الذكرى أولاً');state.memories.unshift(v);state.xp+=10;$('#memoryInput').value='';save();toast('تمت إضافة نجمة جديدة ✦')};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('nebulaLight',document.body.classList.contains('light'))};
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='nebula-world.json';a.click();toast('تم تصدير عالمك')};
$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const n=JSON.parse(r.result);if(!n||!Array.isArray(n.memories))throw 0;state=n;save();toast('تم استيراد العالم ✦')}catch{toast('ملف غير صالح')}};r.readAsText(f)};
$('#resetBtn').onclick=()=>{if(confirm('سيتم حذف عالمك من هذا الجهاز. متأكد؟')){localStorage.removeItem('nebulaState');location.reload()}};
function win(points){state.wins++;state.xp+=points;save();toast(`انتصار! +${points} طاقة ✦`);setTimeout(closeGame,900)}
function openGame(type){$('#modal').classList.add('show');const m=$('#gameMount');m.innerHTML='';({lightning:lightning,maze:maze,orbit:orbit,pulse:pulse}[type])(m)}
function closeGame(){$('#modal').classList.remove('show');$('#gameMount').innerHTML=''}$('#closeModal').onclick=closeGame;$('#modal').onclick=e=>{if(e.target.id==='modal')closeGame()};
$$('.gameBtn').forEach(b=>b.onclick=()=>openGame(b.dataset.game));
function head(title,desc){return `<span class="eyebrow">ARCADE</span><h2>${title}</h2><p>${desc}</p>`}
function lightning(m){m.innerHTML=head('⚡ صائد البرق','اضغط على 15 برقاً. كل ضغطة تغيّر مكان الهدف.')+'<div class="gameStage" id="stage"></div><div class="controls"><b id="sc">0</b> / 15</div>';let n=0,st=$('#stage');function spawn(){st.innerHTML='';let t=document.createElement('button');t.className='target';t.textContent='⚡';t.style.fontSize='42px';t.style.left=Math.random()*88+'%';t.style.top=Math.random()*78+'%';t.onclick=()=>{n++;$('#sc').textContent=n;if(n>=15)win(30);else spawn()};st.appendChild(t)}spawn()}
function maze(m){m.innerHTML=head('🧩 متاهة الضوء','استخدم الأسهم أو WASD للوصول إلى الدائرة الذهبية.')+'<div class="gameStage" id="mz"><div class="mazeBall" id="ball"></div><div class="goal" style="right:22px;bottom:22px">✦</div><div class="wall" style="left:25%;top:0;width:18px;height:65%"></div><div class="wall" style="left:25%;bottom:0;width:55%;height:18px"></div><div class="wall" style="right:25%;top:25%;width:18px;height:65%"></div></div><div class="controls">المسافة: تحرك بالأسهم</div>';let b=$('#ball'),x=18,y=18,won=false;function draw(){b.style.left=x+'px';b.style.top=y+'px';if(x>stW()-70&&y>stH()-70&&!won){won=true;win(40)}}function stW(){return $('#mz').clientWidth}function stH(){return $('#mz').clientHeight}document.onkeydown=e=>{if(!$('#modal').classList.contains('show'))return;let s=12;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')x+=s;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')x-=s;if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')y+=s;if(e.key==='ArrowUp'||e.key.toLowerCase()==='w')y-=s;x=Math.max(0,Math.min(stW()-22,x));y=Math.max(0,Math.min(stH()-22,y));draw()};draw()}
function orbit(m){m.innerHTML=head('🪐 مدار مستقر','اضغط عند اللحظة المناسبة لتبقي الكوكب في مداره.');m.innerHTML+='<canvas class="orbitCanvas" id="oc"></canvas><div class="controls"><button class="btn primary" id="orbBtn">ثبّت المدار</button> <b id="orbSc">0</b></div>';let c=$('#oc'),ctx=c.getContext('2d'),score=0,t=0;function resize(){c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio)}resize();function loop(){if(!$('#modal').classList.contains('show'))return;t+=.025;let w=c.clientWidth,h=c.clientHeight,rx=Math.min(w,h)*.32,ry=rx*.55,cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#ffffff22';ctx.ellipse(cx,cy,rx,ry,0,0,7);ctx.stroke();let px=cx+Math.cos(t)*rx,py=cy+Math.sin(t)*ry;ctx.font='30px sans-serif';ctx.fillText('🪐',px-15,py+10);requestAnimationFrame(loop)}loop();$('#orbBtn').onclick=()=>{let phase=Math.abs(Math.sin(t));if(phase>.94){score++;$('#orbSc').textContent=score;if(score>=5)win(50)}else toast('ليس في مركز المدار… حاول مجدداً')};}
function pulse(m){m.innerHTML=head('🎯 نبضة الهدف','أوقف المؤشر داخل المنطقة الذهبية. ثلاث إصابات للفوز.')+'<div class="pulseTrack"><div class="pulseZone"></div><div class="pulseNeedle" id="needle"></div></div><div class="controls"><button class="btn primary" id="hit">أوقف!</button> <b id="ps">0</b>/3</div>';let n=0,pos=0,dir=1,run=true;function anim(){if(!run)return;pos+=dir*1.8;if(pos>98||pos<0)dir*=-1;$('#needle').style.left=pos+'%';requestAnimationFrame(anim)}anim();$('#hit').onclick=()=>{if(pos>=45&&pos<=57){n++;$('#ps').textContent=n;if(n>=3){run=false;win(35)}}else toast('خارج المنطقة ✕')};}
if(localStorage.getItem('nebulaLight')==='true')document.body.classList.add('light');render();
